// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'wireguard_item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'wireguard_item.g.dart';

@freezed
class WireguardItem with _$WireguardItem {
  const factory WireguardItem({
    required String private_key,
    required String public_key,
    required String preshared_key,
    required String endpoint,
    required List<String> allocated_ips,
    required List<String> allowed_ips,
  }) = _WireguardItem;

  factory WireguardItem.fromJson(Map<String, Object?> json) => _$WireguardItemFromJson(json);
}
