// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'server_item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'server_item.g.dart';

@freezed
class ServerItem with _$ServerItem {
  const factory ServerItem({
    required int id,
    required String name,
    required String country,
    required String flag,
    required double stress,
  }) = _ServerItem;

  factory ServerItem.fromJson(Map<String, Object?> json) => _$ServerItemFromJson(json);
}
