// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZXvsVUGMq1SBGiPxL4I03wcARMbXWZg',
    appId: '1:591551138638:android:d4607bb83600d9fe526c1f',
    messagingSenderId: '591551138638',
    projectId: 'privet-1a0f9',
    storageBucket: 'privet-1a0f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-bl40wpXdjUDwHB7ssW3Bqw9XRSvi90',
    appId: '1:591551138638:ios:e2a07a0eeb97c114526c1f',
    messagingSenderId: '591551138638',
    projectId: 'privet-1a0f9',
    storageBucket: 'privet-1a0f9.appspot.com',
    androidClientId: '591551138638-sq0ap4eorh1meidm2pvenc8vsm6jlv2o.apps.googleusercontent.com',
    iosClientId: '591551138638-f50joc4j3gj66ud8cd059rldhpivam7l.apps.googleusercontent.com',
    iosBundleId: 'com.wireguardDartExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi-bl40wpXdjUDwHB7ssW3Bqw9XRSvi90',
    appId: '1:591551138638:ios:0756c79ad1921fcb526c1f',
    messagingSenderId: '591551138638',
    projectId: 'privet-1a0f9',
    storageBucket: 'privet-1a0f9.appspot.com',
    androidClientId: '591551138638-sq0ap4eorh1meidm2pvenc8vsm6jlv2o.apps.googleusercontent.com',
    iosClientId: '591551138638-1p9ru4vc1jpucsnqi4p5gid3k27aseuh.apps.googleusercontent.com',
    iosBundleId: 'network.mysterium.wireguardDartExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwouGFHn0AiIGhO9O2yftXzAFRF8N16rM',
    appId: '1:591551138638:web:ecc701a92ee8aede526c1f',
    messagingSenderId: '591551138638',
    projectId: 'privet-1a0f9',
    authDomain: 'privet-1a0f9.firebaseapp.com',
    storageBucket: 'privet-1a0f9.appspot.com',
    measurementId: 'G-FQW3F4S7LK',
  );

}