// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'server_tunnel.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'server_tunnel.g.dart';

@freezed
class ServerTunnel with _$ServerTunnel {
  const factory ServerTunnel({
    required String private_key,
    required String public_key,
    required String preshared_key,
    required String name,
    required bool use_server_dns,
    required bool enabled,
    required String created_at,
    required String updated_at,
  }) = _ServerTunnel;

  factory ServerTunnel.fromJson(Map<String, Object?> json) => _$ServerTunnelFromJson(json);
}
